---
title: "Map Thursday"
author: "Leah"
date: "2023-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 
Today we are going to be working with maps. 

# Load Libraries 
```{r}
library(ggmap)
library(tidyverse)
library(here)
library(ggsn)
library(grid)
```

# Load Data 
```{r}
ChemData<-read_csv(here("Week_07","Data","chemicaldata_maunalua.csv"))
glimpse(ChemData)
```
# Get base maps 
```{r}
Oahu <-get_map("Oahu")
ggmap(Oahu)
```
# Get Coordinates from Wailupe on Oahu 
```{r}
WP<-data.frame(lon = -157.7621, lat = 21.27427)
# get base layer 
Map1<-get_map(WP)
# plot it 
ggmap(Map1)
```

# Use ggmap base layer 
```{r}
Map1<-get_map(WP,zoom = 17, maptype = "satellite") 
ggmap(Map1)+
  geom_point(data = ChemData,
             aes(x = Long, y = Lat, color = Salinity),
             size = 4) +
  scale_color_viridis_c() +
   scalebar( x.min = -157.766, x.max = -157.758,
           y.min = 21.2715, y.max = 21.2785,
            dist = 250, dist_unit = "m", model = "WGS84", 
            transform = TRUE, st.color = "white",
            box.fill = c("yellow", "white"))
```

