---
title: 'Intro to Maps: Tuesday'
author: "Leah"
date: "2023-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 
Today we are going over an introduction on how to code maps 

# Load libraries
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
library(ggdogs)
library(ggmap)
```

# Load data 

```{r}
# CA pop data 
popdata<-read_csv(here("Week_07","Data","CApopdata.csv"))
# stars data 
stars<-read_csv(here("Week_07","Data","stars.csv"))
```
# How to pull by layers 
```{r}
world<-map_data("world") # data for entire world 
usa<-map_data("usa") # date for the USA
head(usa)
italy<-map_data("italy") # data for Italy 
head(italy)
states<-map_data("state") # get data for states 
head(states)
counties<-map_data("county") # data for counties 
head(counties)
```
# Make a map of the world 
```{r World Map}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, y = lat, group = group,
                   fill = region), # fill by color 
               color = "black") +# add color to the lines
  guides(fill = FALSE) +
  theme_minimal() + # change the theme 
  theme(panel.background = element_rect(fill = "lightblue")) + # make the ocean blue 
  coord_map(projection = "mercator", #flat earth 
            xlim = c(-180,180))
```
 # Map of California 
```{r Map of California}
head(states)
CA_data <- states %>%
  filter(region == "california")
  ggplot()+
  geom_polygon(data = CA_data,
               aes(x = long, y = lat, group = group),
               color = "black") +
    coord_map() +
    theme_void()
  
head(counties)[1:3,]
head(popdata)
```
 # Fun R package 
```{r}
ggplot(mtcars)+
  geom_dog(aes(mpg, wt), dog = "pug", size = 5)
```
 
