---
title: "Week 12 HW"
author: "Leah"
date: "2023-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "../output/")
```

# Today we are going to be practicing with loops 

# Load Libraries 
```{r}
library(tidyverse)
library(here)
```

# Load Data 
```{r}
hw <- read_csv(here("Week_12", "Data", "homework","TP1.csv"))
glimpse(hw)
```

# Read in Data using loop 
```{r}
HomeworkPath <- here("Week_12","Data","homework") # tell the computer the location 

files <- dir(path = HomeworkPath, pattern = ".csv")
# look only at .csv files 

files # load the files 

```

# Calculate mean and standard deviation of temp and light for each tide pool using loop 
```{r}
homework <- data.frame(matrix(nrow = length(files), ncol = 4)) # make the empty data frame for the 4 columns

colnames(homework) <- c("mean_temp","mean_light","sd_temp","sd_light") # name the columns 

homework 

# Add all the data to the table created 
for (i in 1:length(files)){
raw_loop_data <- read_csv(paste0(HomeworkPath,"/",files[1])) # basic code to calculate mean 
homework$filename[i]<-files[i]
homework$mean_light[i] <- mean(raw_loop_data$Intensity.lux, na.rm = TRUE) # add mean light 
homework$mean_temp[i] <- mean(raw_loop_data$Temp.C, na.rm = TRUE) # add mean temp 
homework$sd_light[i] <- sd(raw_loop_data$Intensity.lux, na.rm = TRUE) # add sd light 
homework$sd_temp[i] <- sd(raw_loop_data$Temp.C, na.rm = TRUE) # add sd temp 
}

mean_temp <- mean(raw_loop_data$Temp.C, na.rm = TRUE) # calculate mean temp 
mean_temp
mean_light <- mean(raw_loop_data$Intensity.lux, na.rm = TRUE) # calculate mean light 
mean_light
sd_temp <- sd(raw_loop_data$Temp.C, na.rm = TRUE)
sd_temp # calculate sd temp 
sd_light <- sd(raw_loop_data$Intensity.lux, na.rm = TRUE) # calculate sd light 
sd_light

homework # load file 

```
# Bring in the files with map and calculate mean 
```{r}


HomeworkPath <- here("Week_12", "Data","homework")
files <- dir(path = HomeworkPath, pattern = ".csv", full.names = TRUE)
# look only at .csv files 

files # load the files 

data <-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "homework") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(homework) %>% # group by homework file name 
  summarise(mean_temp = mean(Temp.C, na.rm = TRUE),
            mean_light = mean(Intensity.lux, na.rm = TRUE),
            sd_temp = sd(Temp.C, na.rm = TRUE),
            sd_light = sd(Intensity.lux, na.rm = TRUE)) # standard deviation of light and temp 

data
```

